import Head from "next/head";
import Layout from "@/components/Layout";
import {
  Box,
  Button,
  Card,
  CardActionArea,
  CardActions,
  CardContent,
  CardMedia,
  Grid,
  Typography,
} from "@mui/material";
import Link from "next/link"
import data from "@/utils/data";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h2 className="border-orange-bottom">Products</h2>
        <Grid container spacing={3}>
          {data?.products?.map((item) => (
            <Grid item md={4} key={item?.name}>
              <Card>
                <Link href={`/product/${item?.slug}`}>
                  <CardActionArea>
                    <CardMedia
                      component="img"
                      image={item?.image}
                      title={item?.name}
                    />
                    <CardContent>
                      <Typography>{item?.name}</Typography>
                    </CardContent>
                  </CardActionArea>
                  <CardActions>
                    <Box>
                      <Typography>${item?.price}</Typography>
                      <Button
                        size="medium"
                        variant="contained"
                        className="buttons"
                      >
                        Add To Basket
                      </Button>
                    </Box>
                  </CardActions>
                </Link>
              </Card>
            </Grid>
          ))}
        </Grid>
      </Layout>
    </>
  );
}
